# Generated by Django 4.2.6 on 2024-01-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_archive_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_archive',
            new_name='is_active',
        ),
    ]
